name: tagpr

on:
  push:
    branches: ["main"]

jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Songmu/tagpr@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
